### ISSUE TITLE
Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-appsvcs-templates#2]
### Environment
 * FAST RPM Version: 1.0.0
 * BIG-IP Version: 15.0

### Summary
I cannot render the fast template on an Ubuntu 18 or OS X 10.15 machine.  When issuing the API call against the BIG-IP I'm told the declaration is invalid.  I'm trying to render the AS3 declaration locally to troubleshoot it.

### Steps To Reproduce
List the steps to reproduce the behavior:
I am following the [FAST Create New Template example]( https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/userguide/template-authoring.html)

### Expected Behavior
An as3 declaration should be rendered

### Actual Behavior
```
/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/node_modules/yargs/yargs.js:1242
      else throw err
           ^

TypeError: Cannot read property 'readFile' of undefined
    at loadParameters (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/cli.js:29:15)
    at loadTemplateAndParameters (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/cli.js:35:5)
    at renderTemplate (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/cli.js:67:58)
    at Object.require.command.command.command.command.argv [as handler] (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/cli.js:138:16)
    at Object.runCommand (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/@f5devcentral/f5-fast-core/cli.js:166:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by zinkem5** [comment]
Hi Cody,

Rendering templates on a local machine, outside of BIG-IP is not currently supported through the FAST Extension.

If you are using the npm module, found here: https://www.npmjs.com/package/@f5devcentral/f5-fast-core , it was updated this week to version 0.5.1. 

Please try upgrading your local fast installation and try again. Community support is provided through the core module issue board here: https://github.com/f5devcentral/f5-fast-core/issues

I will close this issue, if you are still experiencing problems with v0.5.1 of @f5devcentral/f5-fast-core, please file them on the community support board.
